#!/bin/bash -e

# Install firefox from flathub for current user only

flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install --user -y org.mozilla.firefox

# Install ffmpeg-full to solve video lag
flatpak install --user -y org.freedesktop.Platform.ffmpeg-full

# Disable bitmap fonts to avoid fuzzy fonts
# Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1621915

# Create the directory first, or the script will fail
mkdir ~/.var/app/org.mozilla.firefox/config/fontconfig

# Create fonts.conf for the current user
printf '<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <!-- Disable bitmap fonts. -->
    <selectfont><rejectfont><pattern>
        <patelt name="scalable"><bool>false</bool></patelt>
    </pattern></rejectfont></selectfont>
</fontconfig>' > ~/.var/app/org.mozilla.firefox/config/fontconfig/fonts.conf
